name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # It's good practice to define a range

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.20.2 # Using a more standard, recent version
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  
  # Firebase packages
  firebase_core: ^4.0.0 # It's good practice to include firebase_core explicitly
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  # flutter_launcher_icons is a development tool, so it belongs here
  flutter_launcher_icons: ^0.14.4 

flutter:
  uses-material-design: true

# Configuration for the launcher icon package
flutter_launcher_icons:
  android: true
  ios: true
  # Corrected typo: "assets" instead of "assests"
  image_path: "assets/icon/Icon.png"