// File generated by FlutterFire CLI.
// It's recommended not to modify this file manually.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This class is used by the `Firebase.initializeApp()` call in your `main.dart`
/// file to connect your app to the correct Firebase project.
class DefaultFirebaseOptions {
  /// A static getter that returns the correct [FirebaseOptions] for the
  /// current platform (e.g., Android or iOS).
  static FirebaseOptions get currentPlatform {
    // This file does not support web, as it was not selected during configuration.
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // A switch statement to check the platform the app is running on.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // Return the android options
      case TargetPlatform.iOS:
        return ios; // Return the iOS options
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// The specific configuration options for your Android Firebase app.
  /// These keys identify your app to the Firebase backend.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvpo0ItJC0pGALXRPUQqiNlNHwaLmca6I',
    appId: '1:170200412949:android:75207a2cbc03bb58db6f1c',
    messagingSenderId: '170200412949',
    projectId: 'workouttracker-b2bf5',
    storageBucket: 'workouttracker-b2bf5.firebasestorage.app',
  );

  /// The specific configuration options for your iOS Firebase app.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvAG2MqaxLnRUovM97gvcC3zTjYD9nS7U',
    appId: '1:170200412949:ios:964ad0ea0f595d0ddb6f1c',
    messagingSenderId: '170200412949',
    projectId: 'workouttracker-b2bf5',
    storageBucket: 'workouttracker-b2bf5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}